@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.attributetooltipfix;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
